services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0@sha256:9bd81257180e2d5328df1a139c3af76de453d6f2c475235035645c92054a168f
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data

  tallest:
    build:
      dockerfile: docker/dev.Dockerfile
      context: .
