{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: {{ .Release.Name }}-kiwix-serve
    app.kubernetes.io/instance: {{ .Release.Name }}-kiwix-serve
  name: {{ .Release.Name }}-kiwix-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "256Gi" }}
  storageClassName: {{ .Values.persistence.storageClassName | default "local" }}
  volumeMode: Filesystem
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end -}}
{{- end -}}
{{- end -}}
