---
apiVersion: 1.0.0
name: tallest
version: 0.0.2
description: tallest deployment to auto-fetch ZIM repository updates
type: application

dependencies:
  - name: app-template
    alias: tallest
    version: ~4
    repository: https://bjw-s-labs.github.io/helm-charts/
