apiVersion: 1.0.0
name: kiwix
version: 3.7
description: kiwix server w/ simple CSI integration, along with a deployment of go-tallest to auto-fetch ZIM repository updates
type: application

# truly. fuck truecharts.
# dependencies:
#   - name: kiwix-serve
#     version: ~10
#     repository: oci://tccr.io/truecharts
