---
tallest:
  controllers:
    cron:
      type: cronjob
      containers:
        cron:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
          image:
            pullPolicy: Always
            repository: ghcr.io/chr0n1x/tallest
            tag: latest
      cronjob:
        # default once a week
        schedule: "0 0 * * 0"
